### ISSUE TITLE
Humanize Note Placement - not an issue, a suggestion

### ISSUE THREAD

**Issue by NeuroNoNeuro** [JanZaion/chord-spawner#1]
Love this Device - saves me a bunch of time coming up with chords (and patterns!) that I just wouldn’t via other means.  

One request - may we have the capability to have a sort of strum/humanized note placement for the chords?  Sure, I can go in and do it by hand, or use other Devices to place the notes - it would be nice to just do it right from Chord Spawner.  Imprinted right into the MIDI, versus a ‘different every time’ method like using Ableton’s Arpeggiator - https://www.youtube.com/watch?v=iyMsgt2V2zM

I purchased CHORDimist before I found Chord Spawner, and wish I had just found Chord Spawner first.  That being said, CHORDimist has these strumming capabilities that are wonderful to have ‘imprinted’ into the MIDI pattern.  Would there be any possibility for a humanized/strum capability to be added to Chord Spawner?  It’s one of those things that the composer/listener gets accustomed to, and would be great for a repeatable humanized feel.  I can pretend I’m actually a piano player instead of a drummer (haha) :D

Whaddaya say?

**Comment by JanZaion** [comment]
Hi @NeuroNoNeuro , thanks for reaching out. It warms my heart to hear how much you enjoy Chord Spawner!

I sure see usefulness of the feature you suggest, as I found myself humanizing some notes by hand just the other day.

However, I'll probably dissapoint you with the fact that I don't intend to work on Chord Spawner much further. Since it's by far the most popular device I've made, I might concider writing Chord Spawner 2.0, where i will add/subtract features to make the working with the device more streamlined, based on the feedback I got. But no promises, since this is something I do in my free time.

To achieve the humanization, I use this device and I can only recommend it:
https://maxforlive.com/library/device/3448/random-note-delay

I hope you make some awesome tunes and have fun along the way!
